// lang-th.ts

export const LANG_TH_NAME = 'th';

export const LANG_TH_TRANS = {
  'Crm_Login_Header'	:	'เข้าสู่ระบบ'	,
  'Email-id'	:	'อีเมล์'	,
  'Crm_Password'	:	'รหัสผ่าน'	,
  'Crm_Validation_WrongEmailPwd'	:	'อีเมล์หรือรหัสผ่านไม่ถูกต้อง'	,
  'I_have_read_and_agree_to_the'	:	'อ่านและยอมรับ.'	,
  'Login_Please_Enter_Email_and_Password'	:	'กรุณาใส่อีเมล์และรหัสผ่าน'	,
  'By_Logging_in_you_agree_to_our'	:	'โดยการเข้าสู่ระบบคุณเห็นด้วยกับเรา'	,
  'Privacy_Policy'	:	'นโยบายความเป็นส่วนตัว'	,
  'Crm_MT4_Submit'	:	'เสนอ'	,
  'Forgot_Password'	:	'ลืมรหัสผ่าน'	,
  'Verification_Link_Sent'	:	'ส่งลิงก์การยืนยันแล้ว'	,
  'Enter_valid_email'	:	'ป้อนที่อยู่อีเมลที่ถูกต้อง'	,
  'Crm_Footer_Message'	:		'ระยะเวลาและราคาที่แสดงบนเชื่อมต่อเหล่านี้ส่วนใหญ่จะขึ้นอยู่กับความแข็งแรงและความมั่นคงของการเชื่อมต่ออินเทอร์เน็ตของคุณ โปรดดูรายละเอียดการค้าในแพลตฟอร์ม MetaTrader 4 เพื่อให้ได้ผลลัพธ์ที่ถูกต้องที่สุดและครั้งสุดท้าย',
  'Please_Enter_Email'	:	'กรุณาใส่อีเมล์'	,
  'Enter_Email'	:	'กรอกอีเมล์'	,
  'Please_Enter_Password'	:	'กรุณาใส่รหัสผ่าน'	,
  'Please_Accept_Privacy_Policy'	:	'ยอมรับข้อกำหนดและเงื่อนไข'	,
  'Please_enter_your_registered_email'	:	'กรุณากรอกอีเมลที่ลงทะเบียนของคุณ'	,
  'Getting_started_with'	:	'เริ่มต้นด้วย'	,
  'web_tarder_carousel'	:	'เว็บเทรดเดอร์'	,
  'Light_up_your_phone_Trade'	:	'สว่างขึ้นการค้าโทรศัพท์ของคุณ ...'	,
  'Anytime_Anywhere_carousel'	:	'ทุกที่ทุกเวลา  ทุกแห่ง'	,
  'The_Worlds_Most_Advanced'	:	'ก้าวหน้าที่สุดในโลก'	,
  'MT4_FX_Derivatives'	:	'สัญญาซื้อขายล่วงหน้า MT4 FX'	,
  'Binding_MT4_Account'	:	'เข้าสู่ระบบMT4'	,
  'MT4_Password'	:	'รหัสผ่าน'	,
  'MT4_Remember_Me'	:	'จดจำฉัน'	,
  'Powered_by'	:	'ขับเคลื่อนโดย'	,
  'Back_to'	:	'ย้อนกลับ'	,
  'Back_to_Login'	:	'ย้อนกับไปเข้าสู่ระบบ'	,
  'MT4_Submit'	:	'เสนอ'	,
  'Trade_Loading'	:	'กำลังโหลด'	,
  'Trade_Profile'	:	'ข้อมูลส่วนตัว'	,
  'Trade_Trading_History'	:	'ประวัติการซื้อขาย'	,
  'Trade_Deposit'	:	'เงินฝาก'	,
  'Trade_Withdrawal'	:	'การถอนตัว'	,
  'Trade_Settings'	:	'การตั้งค่า'	,
  'Trade_Feedback'	:	'ผลตอบรับ'	,
  'Trade_About_us'	:	'เกี่ยวกับเรา'	,
  'Trade_Logout'	:	'ออกจากระบบ'	,
  'Trade_Search'	:	'ค้นหา'	,
  'Trade_Favorites'	:	'รายการโปรด'	,
  'Trade_No_Favorites'	:	'ไม่พบรายการโปรด'	,
  'Trade_Balance'	:	' Balance'	,
  'Trade_Open_Trades'	:	'เปิดเทรด'	,
  'Trade_History'	:	'ประวัติศาสตร์'	,
  'Trade_Amount'	:	'จำนวน'	,
  'Trade_Profit'	:	'กำไร'	,
  'Trade_OK'	:	'ตกลง'	,
  'Trade_UP'	:	'ขึ้น'	,
  'Trade_DOWN'	:	'ลง'	,
  'Trade_Total_Exosure'	:	'การเปิดรับรวม'	,
  'Trade_One_Click_Trading'	:	'การซื้อขายเพียงคลิกเดียว'	,
  'Trade_Sounds'	:	'เสียง'	,
  'Trade_Language'	:	'ภาษา'	,
  'Trade_Chinese'	:	'ชาวจีน'	,
  'Trade_Confirm_Trade'	:	'ยืนยันการค้า'	,
  'Trade_Submit'	:	'เสนอ'	,
  'Trade_Close'	:	' ปิด'	,
  'Hist_Full_Trade_History'	:	'ประวัติศาสตร์การค้าเต็มรูปแบบ'	,
  'Hist_Showing'	:	'การแสดง'	,
  'Page_number '	:		'',
  'Hist_of'	:	'ของ'	,
  'Hist_Date'	:	'เวลา'	,
  'Hist_Symbol'	:	'สัญลักษณ์'	,
  'Hist_Action'	:	'การกระทำ'	,
  'Hist_Open'	:	'เปิด'	,
  'Hist_Close'	:	' ปิด'	,
  'Hist_Amount'	:	'จำนวน'	,
  'Hist_Profit'	:	'กำไร'	,
  'Hist_Interval'	:	'ช่วงสูง'	,
  'Hist_Result'	:	'ผลลัพธ์'	,
  'Hist_No_History'	:	'ไม่พบประวัติการค้า'	,
  'Hist_Loading'	:	'กำลังโหลด'	,
  'Ind_BB'	:	'Bollinger Bands'	,
  'Ind_MACD'	:	'MACD'	,
  'Ind_Stochastic'	:	' Stochastic'	,
  'Ind_SMA'	:	'SMA'	,
  'Ind_RSI'	:	'RSI'	,
  'Ind_EMA'	:	'EMA'	,
  'Ind_SETTINGS'	:	'การตั้งค่า'	,
  'Ind_OK'	:	'ตกลง'	,
  'Ind_Close'	:	'ปิด'	,
  'Open_Open_Positions'	:	'เปิดตำแหน่ง'	,
  'Open_NO_Trade'	:	'ไม่มีการซื้อขายที่เปิดอยู่'	,
  'Open_Open'	:	'เปิด'	,
  'Open_Close'	:	'ปิด'	,
  'Open_Amount'	:	'จำนวน'	,
  'Open_Profit'	:	'กำไร'	,
  'Win'	:	'ชนะ'	,
  'Loss'	:	'ขาดทุน'	,
  'Draw'	:	'ได้รับ'	,
  'BB'	:	'BOLLINGER BANDS'	,
  'MACD'	:	' MACD'	,
  'STOCHASTIC'	:	' STOCHASTIC'	,
  'SMA'	:	'SMA'	,
  'RSI'	:	' RSI'	,
  'EMA'	:	' EMA'	,
  'OVERSOLD'	:	'ขายมากจนเกินไป'	,
  'OVERBOUGHT'	:	'ซื้อมากจนเกินไป'	,
  'Period'	:	'ระยะเวลา'	,
  'UNDEFINED'	:	'ไม่ได้กำหนด'	,
  'SIGNAL PERIOD'	:	'ระยะเวลาสัญญาณ'	,
  'FAST PERIOD'	:	'ระยะเวลาที่รวดเร็ว'	,
  'SLOW PERIOD'	:	'ระยะเวลาช้า'	,
  'PERIOD'	:	'ระยะเวลา'	,
  'STANDARD DEVIATION'	:	'ส่วนเบี่ยงเบนมาตรฐาน'	,
  'K PERIOD'	:	'ระยะเวลา K'	,
  'D PERIOD'	:	'ระยะเวลา D'	,
  'Trade_Double_Up'	:	'สองครั้งขึ้น'	,
  'Trade_Min_Amount'	:	'จำนวนเงินขั้นต่ำ'	,
  'Trade_Max_Amount'	:	'จำนวนเงินสูงสุด'	,
  'Trade_Insufficient_Account_Balance'	:	'ยอดเงินในบัญชีไม่เพียงพอ'	,
  'Trade_Amount_Range_1'	:	'จำนวนเงินจะต้องอยู่ในช่วงของ'	,
  'Trade_Amount_Range_2'	:	'ไปยัง'	,
  'Trade_Amount_Range_3'	:		' ',
  'Trade_Amount_Multiples_Of'	:	'จำนวนต้องเป็นทวีคูณ'	,
  'Trade_Amount_Multiples_Of_After'	: '',
  'Trade_Too_many_orders'	:	'มีคำสั่งซื้อมากเกินไป'	,
  'Trade_Market_is_closed'	:	'ตลาดปิด'	,
  'Trade_Invalid_parameters'	:	'พารามิเตอร์ไม่ถูกต้อง'	,
  'Trade_Submit_order_failure'	:	'ไม่สามารถสั่งซื้อได้ในขณะนี้'	,
  'Trade_Invalid_Amount'	:	'จำนวนเงินไม่ถูกต้อง'	,
  'Trade_Account_Inactive'	:	'สถานะ MT4 ของคุณไม่ได้ใช้งานโปรดติดต่อฝ่ายบริการลูกค้า'	,
  'Internet_connection_is_slow'	:	'การเชื่อมต่ออินเทอร์เน็ตช้า'	,
  'Internet_connection_is_lost_Reconnecting'	:	'การเชื่อมต่ออินเทอร์เน็ตขาดหายไป  เชื่อมต่อใหม่ ....'	,
  'Connecting'	:	'การเชื่อมต่อ'	,
  'Your_session_will_expire_in_next'	:	'เซสชั่นของคุณจะหมดอายุในครั้งต่อไป'	,
  'Trade_seconds'	:	'วินาที'	,
  'Trade_Not_enough_money'	:	'ยอดเงินไม่เพียงพอ'	,
  'Trade_Reached_Max_Chart_Tabs'	:	'มาถึงแท็บแผนภูมิสูงสุดแล้ว'	,
  'Trade_Order_placed_successfully'	:	'ส่งคำสั่งซื้อเรียบร้อยแล้ว'	,
  'The_Reset_Password_Link_has_been_sent_to_your_email'	:	'ลิงค์รหัสผ่านรีเซ็ตถูกส่งไปยังอีเมลของคุณแล้ว'	,
  'Please_Enter_email_address'	:	'กรุณาใส่ที่อยู่อีเมล'	,
  'Trade_deposit_rediret'	:	'คุณจะถูกนำไปที่ CRM เพื่อการฝาก'	,
  'Trade_withdrawal_redirect'	:	'คุณจะถูกนำไปที่ CRM เพื่อการถอน'	,
  'Trade_Sure'	:	'แน่ใจ'	,
  'Trade_not_now'	:	'ไม่ใช่ตอนนี้'	,
  'Trade_No_Symbols_Found'	:	'ไม่พบสัญลักษณ์'	,
  'Log_Out_Mssg'	:	'คุณจะออกจากระบบคุณต้องการดำเนินการต่อหรือไม่'	,
  'MT4_Password_Incorrect'	:	'รหัสผ่านผิดพลาด'	,
  'Max_Indicators'	:	'อนุญาตให้ใช้ตัวบ่งชี้ได้สูงสุด 3 ตัวต่อครั้ง'	,
  'Bookmark_Chart'	:	'คั่นหน้าแผนภูมิที่คุณชื่นชอบที่นี่'	,
  'Trade_Chart_Bookmarked'	:	'แผนภูมิถูกบุ๊กมาร์กแล้ว'	,
  'MACD_Fast_Period_Greater_Than_Slow_Period'	:	'ช่วงเวลาที่รวดเร็วควรน้อยกว่าช่วงเวลาที่ช้า'	,
  'Bookmark_Added'	:	'เพิ่มบุ๊คมาร์คแล้ว'	,
  'Orientation_wait'	:	'รอสักครู่...'	,
  'Orientation_rotate_landscape'	:	'หมุนหน้าจอเป็นโหมดแนวนอนเพื่อประสบการณ์การใช้งานที่ดียิ่งขึ้น'	,
  'Orientation_note'	:	'บันทึก'	,
  'mobiledevice_line1'	:	'แพลตฟอร์มการซื้อขายครบวงจร'	,
  'mobiledevice_line2'	:	'ยังมีให้ใช้งานในแอพ Android'	,
  'mobiledevice_download_app'	:	'ดาวน์โหลดเดี๋ยวนี้'	,
  'Verified'	:	'ตรวจสอบแล้ว'	,
  'Not_Verified'	:	'ยังไม่ยืนยัน'	,
  'Citizenship'	:	'สัญชาติ'	,
  'Profile'	:	'ข้อมูลส่วนตัว'	,
  'withdrawal_heading'	:	'การถอนตัว'	,
  'register'	:	'สมัครตอนนี้'	,
  'Bankwire_Deposit_Success'	:	'ส่งเงินฝากเรียบร้อยแล้ว !!'	,
  'promoCodePlaceholder'	:	'รหัสโปรโมชั่ (ถ้าต้องการ)'	,
  'get_email_otp'	:	'รับอีเมล OTP'	,
  'check your email'	:	'ตรวจสอบอีเมลของคุณ'	,
  'tosAgreeLabel'	:	'ฉันได้อ่านทำความเข้าใจและยอมรับ'	,
  'termsOfServices'	:	'เงื่อนไขการบริการ'	,
  'email_otp_sent'	:	'ส่งอีเมล OTP แล้ว'	,
  'countryPlaceholder'	:	'ประเทศ'	,
  'phoneCodePlaceholder'	:	'รหัสโทรศัพท์'	,
  'phonePlaceholder'	:	'หมายเลขโทรศัพท์'	,
  'getEmailOtp'	:	'รับอีเมล OTP'	,
  'emailOTPSent'	:	'ส่งอีเมล OTP แล้ว'	,
  'newRegisterCaptchaMsg'	:	'คุณพยายามเข้าสู่ระบบหลายครั้งเกินไปโดยใช้รหัสอีเมลที่ไม่ถูกต้อง  โปรดยืนยันตัวตนของคุณโดยป้อนตัวอักษรที่คุณเห็นในภาพด้านล่าง'	,
  'newRegisterCaptchaMsg2'	:	'สำหรับความช่วยเหลือเพิ่มเติมกรุณาติดต่อ'	,
  'typeTheText'	:	'พิมพ์ข้อความ'	,
  'Please_Select_Country'	:	'กรุณาเลือกประเทศของคุณ'	,
  'Please_Enter_Phone'	:	'กรุณาใส่หมายเลขโทรศัพท์'	,
  'Please_Enter_PhoneCode'	:	'กรุณาใส่รหัสประเทศของคุณ'	,
  'Form_incomplete'	:	'กรุณากรอกข้อมูลให้ครบทุกช่อง'	,
  'Incorrect_Password'	:	'รหัสผ่านไม่ถูกต้อง'	,
  'trade_Deposit_funds'	:	'ทำการฝากเงิน'	,
  'deposit_funds_start_trading'	:	'ฝากเงินเพื่อเริ่มการซื้อขาย'	,
  'deposit_fund_easy'	:	'การฝากเงินเป็นเรื่องง่ายรวดเร็วและมาพร้อมกับไม่มีค่าใช้จ่ายเพิ่มเติม  เริ่มต้นที่ต่ำเพียง $5'	,
  'deposit_funds_now'	:	'ฝากเงินทันที'	,
  'note_portal'	:	'บันทึก'	,
  'otpExpired'	:	'OTP หมดอายุแล้ว  โปรดขอ OTP อีกครั้ง'	,
  'emailValidationErrorMessage'	:	'กรุณาใส่อีเมล์ที่ถูกต้อง'	,
  'emailAlreadyExists'	:	'อีเมล์มีอยู่แล้ว'	,
  'invalidPhoneNumber'	:	'หมายเลขโทรศัพท์ของคุณไม่ถูกต้อง'	,
  'wrongOTP'	:	'ผิด OTP'	,
  'invalidCaptcha'	:	'CAPTCHA ไม่ถูกต้อง'	,
  'otpSentOnYourEmail'	:	'OTP ส่งในอีเมลของคุณ'	,
  'alreadyExists'	:	'บันทึกมีอยู่แล้ว'	,
  'registrationFailed'	:	'การลงทะเบียนไม่สำเร็จ.  กรุณาลองอีกครั้ง.'	,
  'operationFailed'	:	'เกิดข้อผิดพลาดบางอย่าง  กรุณาลองอีกครั้ง.'	,
  'spreadRewards'	:	'กระจายคำและรับรางวัล'	,
  'referralText'	:	'เมื่อมีคนลงทะเบียนกับลิงค์ผู้แนะนำของคุณคุณจะได้รับค่าคอมมิชชั่นจากปริมาณการซื้อขายของพวกเขา'	,
  'shareLink'	:	'แบ่งปันลิงค์อ้างอิงของคุณ'	,
  'copy'	:	'สำเนา'	,
  'scanRQCode'	:	'สแกนรหัส QR นี้สำหรับลิงค์ผู้อ้างอิงของคุณ'	,
  'invalidPromoCode'	:	'ต้องไม่มีตัวอักษรหรืออักขระพิเศษ'	,
  'manage-account'	:	'จัดการบัญชีของคุณ'	,
  'referral'	:	'การอ้างอิง'	,
  'time-frame'	:	'กำหนดเวลา'	,
  'percentage'	:	'เป็นเปอร์เซ็นต์'	,
  'predict'	:	'ล่วงหน้า'	,
  'languageName'	:	'อังกฤษ'	,
  'AZ'	:	' A-Z'	,
  'passwordLengthValidation'	:	'8-31 ตัว'	,
  'az'	:	' a-z'	,
  'passwordNumberValidation'	:	'ตัวเลข'	,
  'noSpecialCharacterLabel'	:	'ไม่มีตัวอักษรพิเศษ'	,
  'enter-otp'	:	'ป้อนอีเมล OTP'	,
  'signIn'	:	'ลงชื่อเข้าใช้'	,
  'home'	:	'บ้าน'	,
  'loginHeading'	:	'ยินดีต้อนรับกลับ!  เข้าสู่ระบบเพื่อเริ่มการซื้อขาย'	,
  'already_using_crypto_countdown'	:	'ใช้งาน Countdown อยู่แล้ว?'	,
  'getStarted'	:	'เริ่ม'	,
  'bannerHeadTitle'	:	'การล่วงหน้าแนวโน้มราคาและรับผลตอบแทนสูงถึง 80%'	,
  'bannerContent'	:	'Countdown เป็นแพลตฟอร์มการซื้อขายทางเว็บที่ให้รางวัลแก่คุณในการทำนายทิศทางราคาของคู่การซื้อขายใด ๆ ที่ใช้ได้อย่างถูกต้อง  มันง่ายเหมือนการคลิกขึ้นหรือลง'	,
  '// bannersubContent'	:	'มันง่ายเหมือนการคลิกขึ้นหรือลง'	,
  'subscribeText'	:	'สร้างบัญชี.  ใช้เวลาเพียง 30 วินาที'	,
  'topValue'	:	' $ 950000+'	,
  'topTraderText'	:	'จ่ายออกในเดือนที่แล้ว  เริ่มการซื้อขายและรับผลตอบแทนที่ดีกลับบ้าน'	,
  'topTraderHead '	:	'ผู้ค้าอันดับต้น ๆ'	,
  'whaleAssuredTitle '	:	'<ชื่อแบรนด์> มั่นใจ'	,
  'whaleRiskFree '	:	'เงินฝากที่ปลอดภัย 100% กำไรแบบเรียลไทม์และการถอนแบบไม่ยุ่งยาก'	,
  'convenientPayments '	:	'วิธีการชำระเงินหลายวิธี'	,
  'professionalWorldClassHead'	:	'แพลตฟอร์มการซื้อขายระดับโลกที่ทำให้คุณชนะ'	,
  'onBodingText '	:	'การนับถอยหลังทำให้ง่ายสำหรับคุณที่จะได้รับผลตอบแทนที่น่าสนใจจากการลงทุนของคุณ  เรียบง่ายแม่นยำและปลอดภัยสูง  ด้วยการถอนเงินอย่างรวดเร็วและการซื้อขายด้วยคลิกเดียวนี่คือทางออกที่ดีที่สุดในการโจมตีทอง'	,
  'tradeUtmostHead'	:	'ซื้อขายด้วยความมั่นใจสูงสุด'	,
  'tradeFirstHead'	:	'รับสิ่งที่ดีที่สุดของทั้งสองโลก'	,
  'tradeFirstText'	:	'<แบรนด์เนม> ประสบการณ์ที่หยั่งรากลึกในด้านการเงินแบบดั้งเดิมและนวัตกรรมที่โดดเด่นในสภาพแวดล้อม fintech ร่วมสมัยมอบสิ่งที่ดีที่สุดสำหรับคุณทั้งสองโลก'	,
  'tradeFirstHead2'	:	'ดำน้ำลึกในสิ่งจำเป็นในการซื้อขาย'	,
  'tradeFirstText2'	:	'รับคู่มือการซื้อขายฟรีเมื่อคุณลงทะเบียนเพื่อทำความเข้าใจพื้นฐานของการนับถอยหลัง crypto'	,
  'hello_there'	:	'สวัสดี!  บอกเราเกี่ยวกับตัวคุณอีกเล็กน้อย'	,
  'account_details'	:	'รายละเอียดบัญชี'	,
  'contact_details'	:	'รายละเอียดการติดต่อ'	,
  'security_details'	:	'รายละเอียดความปลอดภัย'	,
  'new_to_crypto_countdown '	:	'ใหม่ถึงนับถอยหลัง'	,
  'jing-sheng-textimonial'	:	'แอปพลิเคชั่นที่ยอดเยี่ยมสำหรับการซื้อขาย  ฉันซื้อขายมาเป็นเวลานานในการแลกเปลี่ยนและใช้แหล่งข้อมูลที่หลากหลาย  ในแอปพลิเคชันจะมีข้อมูลที่เป็นประโยชน์มากมาย  สิ่งสำคัญที่สุดคือคุณสามารถติดตามสถิติ'	,
  'read-more-reviews'	:	'อ่านความคิดเห็นเพิ่มเติม'	,
  'copyright-text-content'	:	'ห้ามทำซ้ำส่วนของเว็บไซต์นี้โดยไม่ได้รับอนุญาต'	,
  'copyright-text'	:	'ลิขสิทธิ์© 2019 <ชื่อแบรนด์>  สงวนลิขสิทธิ์.'	,
  'copyright-text-2'	:	'ห้ามทำซ้ำส่วนของเว็บไซต์นี้โดยไม่ได้รับอนุญาต'	,
  'stay-assured'	:	'อยู่อย่างมั่นใจ  คุณจะอยู่ใน บริษัท ที่ดี!'	,
  'Create_Password'	:	'สร้างรหัสผ่าน'	,
  'xuxin-textimonial'	:	'ฉันไม่รู้ว่าโบรกเกอร์สำคัญอะไร แต่สำหรับฉันแล้วสิ่งสำคัญที่สุดคือความไว้วางใจและความซื่อสัตย์  ฉันได้ทำงานกับ <ชื่อแบรนด์เนม> ตั้งแต่เดือนธันวาคม 2559 ในตอนแรกกลยุทธ์ของฉันไม่ทำงาน แต่เมื่อเร็ว ๆ นี้ฉันสามารถสร้างผลกำไรที่สม่ำเสมอและสม่ำเสมอ'	,
  'houan-textimonial'	:	'ฉันเริ่มต้นด้วย $ 257.49 ใน 11 มกราคม ถอนตัวออก $ 823.96 ของกำไร 12 กุมภาพันธ์ ฉันจะทำให้การซื้อขายในเวลากลางคืน - ไม่เคยในระหว่างวัน และมันไม่ได้เป็นทุกคืนอย่างใดอย่างหนึ่ง ผมชอบวิธีการเปลี่ยนแปลงราคาคำนวณถึง 6 ตำแหน่งทศนิยมให้ฉันออกมาข้างหน้าเกี่ยวกับข้อเสนออื่น ๆ',
  'usp-heading'	:	'การนับถอยหลังสามารถเป็นเส้นทางที่ง่ายสู่ความสำเร็จ'	,
  'usp-1-title'	:	'ถอนเงินด่วน'	,
  'usp-1-des'	:	'ถอนเงินออกอย่างรวดเร็วด้วยวิธีการต่างๆ  ไม่มีค่าธรรมเนียมแอบแฝง'	,
  'usp-2-title'	:	'เวลาหมดอายุที่ยืดหยุ่น'	,
  'usp-2-des'	:	'เลือกจากช่วงเวลา 7 เวลาที่เริ่มต้นจากเพียง 60 วินาทีเป็นระยะเวลานานเป็นชั่วโมง'	,
  'usp-3-title'	:	'ซื้อขายได้ทุกที่'	,
  'usp-3-des'	:	'แลกเปลี่ยนทุกที่ทุกเวลาด้วยแอปของเรา'	,
  'usp-4-title'	:	'ผลตอบแทนสูง'	,
  'usp-4-des'	:	'ด้วยการลงทุนขั้นต่ำที่ต่ำรับผลตอบแทนสูงถึง 80%'	,
  'usp-5-title'	:	'Tailormade สำหรับ Crypto'	,
  'usp-5-des'	:	'ผู้ประกอบการค้านับถอยหลังเท่านั้นที่ทุ่มเทให้กับ cryptocurrency'	,
  'usp-6-title'	:	'แนะนำและรับ'	,
  'usp-6-des'	:	'แผนการให้รางวัลผู้อ้างอิงที่ดีที่สุดในอุตสาหกรรม  แนะนำเพื่อนของคุณและรับค่าคอมมิชชั่นแม้ว่าคุณจะไม่ได้ซื้อขาย'	,
  'usp-7-title'	:	'ตามด้วยตัวอย่าง'	,
  'usp-7-des'	:	'ติดตามผู้จัดการกลยุทธ์ชั้นนำ  เราสร้างเส้นทางของคุณสู่ผลกำไรได้ง่ายเพียงกดปุ่มไม่กี่ปุ่ม'	,
  'usp-8-title'	:	'ทางเลือกที่กว้างที่สุดของคู่นับถอยหลัง'	,
  'usp-8-des'	:	'เลือกที่จะลงทุนในสกุลเงินดิจิตอลที่หลากหลายด้วยการคลิกเพียงไม่กี่ครั้ง'	,
  'support-heading'	:	'ทางออกที่ดีที่สุดของคุณที่จะได้รับผลตอบแทนที่ดีจริงๆได้อย่างง่ายดาย'	,
  'support-1-title'	:	'แบ่งปันผลกำไรที่น่าสนใจ'	,
  'support-1-des'	:	'เป็นส่วนหนึ่งของการแลกเปลี่ยนในอุตสาหกรรมที่แบ่งปันผลกำไรการซื้อขายผ่านระบบโทเค็นที่ไม่เหมือนใคร'	,
  'support-2-title'	:	'การสนับสนุน LiveChat'	,
  'support-2-des'	:	'ติดอยู่ในระหว่างการค้าหรือไม่?  รับการสนับสนุนทันทีด้วย LiveChat'	,
  'support-3-title'	:	'คู่มือการซื้อขายฟรี'	,
  'support-3-des'	:	'เราอยู่ที่นั่นเพื่อนำทางคุณ  คู่มือการซื้อขายรู้เท่าทันสำหรับคุณเมื่อคุณสมัครใช้งาน'	,
  'talking-about'	:	'มีใครพูดถึงเราอีกบ้าง?'	,
  'disclaimer'	:	'คำปฏิเสธ'	,
  'disclaimer-des'	: 'การดำเนินงานที่ได้รับจากเว็บไซต์นี้อาจดำเนินการระดับสูงของความเสี่ยงและการดำเนินการของพวกเขาเกิดขึ้นในตลาดที่มีความผันผวนสูง ในกรณีของการซื้อของเครื่องมือทางการเงินที่นำเสนอโดยเว็บไซต์และบริการที่คุณอาจได้รับความเสียหายอย่างมีนัยสำคัญของการลงทุนหรือแม้กระทั่งการสูญเสียเงินทั้งหมดในบัญชีของคุณ โปรดดำเนินการระมัดระวังและใช้ความฉลาดรอบคอบของคุณก่อนที่จะตัดสินใจในการลงทุนเงินทุนในตลาด',
  'shanghai'	:	'เซี่ยงไฮ้'	,
  'money-fair'	:	'เงินยุติธรรม'	,
  'awards'	:	'รางวัล'	,
  'trader'	:	'ผู้ประกอบการค้า'	,
  'choice'	:	'ทางเลือก'	,
  'demoAccountCannotProceed'	:	'เปลี่ยนเป็นบัญชีจริงเพื่อดำเนินการต่อ'	,
  'traningAccount'	:	'บัญชีฝึกอบรม'	,
  'traningAccountContent'	:	'บัญชีการฝึกอบรมช่วยให้คุณสามารถแลกเปลี่ยนโดยใช้เงินเสมือนจริง  มียอดคงเหลือ 100,000 USD  คุณไม่สามารถถอนเงินออกจากบัญชีฝึกอบรมของคุณ'	,
  'realAccount'	:	'บัญชี  ของคุณ'	,
  'addMoney'	:	'เพิ่มเงิน'	,
  'tryNow'	:	'ลองตอนนี้'	,
  'selectText'	:	'เลือก'	,
  'selectedText'	:	'เลือก'	,
  'in-usd'	:	'เป็น USD'	,
  'brand-name'	:	'myWhale'	,
  'fullName'	:	'ชื่อเต็ม'	,
  'Please_Enter_Name'	:	'กรุณากรอกชื่อเต็ม'	,
  'nameValidationErrorMessage'	:	'กรุณาใส่ชื่อเต็มที่ถูกต้อง  ต้องไม่มีตัวเลขหรืออักขระพิเศษ',
  'coachMarkStep1':'ยินดีต้อนรับสู่บัญชีทดลองของคุณ  สำรวจว่าการซื้อขาย countdown ของ crypto จริงนั้นเกิดขึ้นได้อย่างไรโดยไม่ต้องฝากเงินจริง',
  'coachMarkStep2':'เลือกคู่สกุลเงินที่คุณต้องการลองซื้อขาย',
  'coachMarkStep3':'นี่คือระยะเวลาที่การค้าของคุณจะดำเนินต่อไปและส่วนแบ่งกำไรที่คุณจะได้รับจากมัน',
  'coachMarkStep4':'เลือกจำนวนเงินที่คุณต้องการลงทุนในการค้านี้',
  'coachMarkStep5':'กำไรที่แสดงไว้ที่นี่เป็นรางวัลที่คุณจะได้รับสำหรับการซื้อขายนี้',
  'coachMarkStep6':'ล่วงหน้าว่าคู่สกุลเงินที่คุณเลือกจะทำงานอย่างไรในช่วงระยะเวลาของการซื้อขาย  มันจะเพิ่มขึ้นหรือมันจะเลื่อนลงมา?  มันง่ายอย่างที่คิด',
  'coachMarkStep7':'เมื่อพร้อมแล้วคุณสามารถเปลี่ยนเป็นบัญชีจริงได้ที่นี่.',
  'next':'ต่อไป',
  'prev':'ก่อน',
  'done':'Done',
  'skip':'Skip',
  "releaseVersion": "รุ่นที่วางจำหน่าย",
  "orderId": "รหัสคำสั่งซื้อ",
  "marketWatch": "Market Watch",
  "invalidPromoCodeValue": "Promocode ไม่ควรเกิน 2,147,483,647"
};
