// lang-vi.ts

export const LANG_VI_NAME = 'vi';

export const LANG_VI_TRANS = {
"Crm_Login_Header":"Đăng nhập",
"Email-id":"Email",
"Crm_Password":"Mật khẩu",
"Crm_Validation_WrongEmailPwd":"Email và mật khẩu không hợp lệ",
"I_have_read_and_agree_to_the":"Tôi đã đọc và đồng ý với",
"Login_Please_Enter_Email_and_Password":"Xin vui lòng nhập email và mật khẩu",
"By_Logging_in_you_agree_to_our":"Đăng nhập để đồng ý với chúng tôi",
"Privacy_Policy":"Chính sách bảo mật",
"Crm_MT4_Submit":"Gửi",
"Forgot_Password":"Quên mật khẩu",
"Verification_Link_Sent":"Liên kết xác nhận đã được gửi",
"Enter_valid_email":"Nhập email hợp lệ",
"Crm_Footer_Message":"Thời gian và giá cả được hiển thị trên các giao diện này chủ yếu phụ thuộc vào tốc độ và sự ổn định của kết nối internet của bạn.",
"Please_Enter_Email":"Xin vui lòng nhập email",
"Enter_Email":"Nhập email",
"Please_Enter_Password":"Xin vui lòng nhập mật khẩu",
"Please_Accept_Privacy_Policy":"Chấp nhận các điều khoản và điều kiện/",
"Please_enter_your_registered_email":"Xin vui lòng nhập email đã đăng ký",
"Getting_started_with":"Bắt đầu với",
"web_tarder_carousel":"Web giao dịch",
"Light_up_your_phone_Trade":"Làm sáng điện thoại bạn cho giao dịch ...",
"Anytime_Anywhere_carousel":"Mọi lúc . Mọi nơi",
"The_Worlds_Most_Advanced":"Thế giới nâng cao",
"MT4_FX_Derivatives":"Công cụ phái sinh MT4 FX",
"Binding_MT4_Account":" MT4 đăng nhập",
"MT4_Password":"Mật khẩu",
"MT4_Remember_Me":"Ghi nhớ tôi",
"Powered_by":"Được cung cấp bởi",
"Back_to":"Quay lại đến",
"Back_to_Login":"Quay lại để đăng nhập",
"MT4_Submit":"Gửi",
"Trade_Loading":"Đang tải",
"Trade_Profile":"Hồ sơ",
"Trade_Trading_History":"LỊCH SỬ GIAO DỊCH",
"Trade_Deposit":"Nạp tiền",
"Trade_Withdrawal":"Rút tiền",
"Trade_Settings":"Cài đặt",
"Trade_Feedback":"Phản hồi",
"Trade_About_us":"Về chúng tôi",
"Trade_Logout":"Đăng xuất",
"Trade_Search":"Tìm kiếm",
"Trade_Favorites":"Yêu thích",
"Trade_No_Favorites":"Không tìm thấy yêu thích",
"Trade_Balance":"Số dư",
"Trade_Open_Trades":"Mở giao dịch",
"Trade_History":"Lịch sử",
"Trade_Amount":"Số lượng",
"Trade_Profit":"Lợi nhuận",
"Trade_OK":"Ok",
"Trade_UP":"Lên",
"Trade_DOWN":"Xuống",
"Trade_Total_Exosure":"Mở ra tất cả",
"Trade_One_Click_Trading":"Nhấn một lần để giao dịch",
"Trade_Sounds":"Âm thanh",
"Trade_Language":"Ngôn ngữ",
"Trade_Chinese":"Trung Quốc",
"Trade_Confirm_Trade":"Xác nhận giao dịch",
"Trade_Submit":"Gửi ",
"Trade_Close":"Đóng",
"Hist_Full_Trade_History":"Lịch sử giao dịch",
"Hist_Showing":"Đang hiển thị",
"Page_number ":"",
"Hist_of":"của",
"Hist_Date":"Ngày",
"Hist_Symbol":"Biểu tượng",
"Hist_Action":"Hoạt động",
"Hist_Open":"Mở",
"Hist_Close":"Đóng",
"Hist_Amount":"Số lượng",
"Hist_Profit":"Lợi nhuận",
"Hist_Interval":"Khoảng cao",
"Hist_Result":"Kết quả",
"Hist_No_History":"Lịch sử giao dịch không tìm thấy",
"Hist_Loading":"Đang tải",
"Ind_BB":" Bollinger Bands",
"Ind_MACD":"MACD",
"Ind_Stochastic":" Stochastic",
"Ind_SMA":" SMA",
"Ind_RSI":" RSI",
"Ind_EMA":" EMA",
"Ind_SETTINGS":"Cài đặt",
"Ind_OK":"OK",
"Ind_Close":"Đóng ",
"Open_Open_Positions":"Mở vị trí",
"Open_NO_Trade":"Không có giao dịch nào đang mở",
"Open_Open":"Mở ",
"Open_Close":"Đóng ",
"Open_Amount":"Số lượng",
"Open_Profit":"Lợi nhuận",
"Win":"Thắng",
"Loss":"Thua",
"Draw":"Hòa",
"BB":" BOLLINGER BANDS",
"MACD":" MACD",
"STOCHASTIC":" STOCHASTIC",
"SMA":" SMA",
"RSI":" RSI",
"EMA":" EMA",
"OVERSOLD":"Quá bán",
"OVERBOUGHT":"Quá mua",
"Period":"Chu kỳ",
"UNDEFINED":"Chưa xác định",
"SIGNAL PERIOD":"Chu kỳ tín hiệu",
"FAST PERIOD":"Chu kỳ nhanh",
"SLOW PERIOD":"Chu kỳ chậm",
"PERIOD":"Chu kỳ",
"STANDARD DEVIATION":"Độ lệch chuẩn",
"K PERIOD":"Chu kỳ K",
"D PERIOD":"Chu kỳ D",
"Trade_Double_Up":"Nhân đôi",
"Trade_Min_Amount":"Số lượng tối thiểu",
"Trade_Max_Amount":"Số lượng tối đa",
"Trade_Insufficient_Account_Balance":"Số dư tài khoản không đủ",
"Trade_Amount_Range_1":"số tiền phải nằm trong phạm vi",
"Trade_Amount_Range_2":"đến",
"Trade_Amount_Range_3":" ",
"Trade_Amount_Multiples_Of":"Số lượng phải là cấp số nhân của",
"Trade_Amount_Multiples_Of_After":"",
"Trade_Too_many_orders":"Quá nhiều lệnh",
"Trade_Market_is_closed":"Thị trường đang đã đóng cửa",
"Trade_Invalid_parameters":"Thông số không hợp lệ",
"Trade_Submit_order_failure":"Không thể đặt lệnh ngay bây giờ",
"Trade_Invalid_Amount":"Số lượng không hợp lệ",
"Trade_Account_Inactive":"Trạng thái MT4 của bạn không hoạt động, vui lòng liên hệ với bộ phận chăm sóc khách hàng",
"Internet_connection_is_slow":"Kết nối kém",
"Internet_connection_is_lost_Reconnecting":"Mất kết nối. Đang kết nối lại...",
"Connecting":"Đang kết nối...",
"Your_session_will_expire_in_next":"Phiên của bạn sẽ hết hạn trong ",
"Trade_seconds":"giây",
"Trade_Not_enough_money":"Số dư không đủ",
"Trade_Reached_Max_Chart_Tabs":" Đã tối đa cửa sổ biểu đồ",
"Trade_Order_placed_successfully":"Đặt lệnh thành công",
"The_Reset_Password_Link_has_been_sent_to_your_email":"Liên kết cài đặt lại mật khẩu đã được gửi đến email của bạn",
"Please_Enter_email_address":"Xin vui lòng nhập địa chỉ email",
"Trade_deposit_rediret":"Bạn sẽ được chuyển tiếp đến CRM để nạp tiền",
"Trade_withdrawal_redirect":"Bạn sẽ được chuyển tiếp đến CRM để rút tiền",
"Trade_Sure":"Chắc chắn",
"Trade_not_now":"Không phải bây giờ",
"Trade_No_Symbols_Found":"Không có biểu tượng nào được tìm thấy",
"Log_Out_Mssg":"Bạn sẽ bị đăng xuất, bạn có muốn tiếp tục ?",
"MT4_Password_Incorrect":"Mật khẩu không hợp lệ",
"Max_Indicators":"Tối đa 3 chỉ số tại một thời điểm được cho phép",
"Bookmark_Chart":"Đánh dấu biểu đồ yêu thích của bạn ở đây",
"Trade_Chart_Bookmarked":"Biểu đồ đã được đánh dấu",
"MACD_Fast_Period_Greater_Than_Slow_Period":"Chu kỳ nhanh hơn nên ít hơn chu kỳ chậm",
"Bookmark_Added":"Đã thêm đánh dấu",
"Orientation_wait":"Xin vui lòng đợi chút ...",
"Orientation_rotate_landscape":"Xoay màn hình sang chế độ ngang để có trải nghiệm người dùng tốt hơn.",
"Orientation_note":"Lưu ý",
"mobiledevice_line1":"Nền tảng giao dịch một cửa",
"mobiledevice_line2":"cũng có sẵn dưới dạng ứng dụng Android.",
"mobiledevice_download_app":"Tải ngay",
"Verified":"Đã xác thực",
"Not_Verified":"Chưa xác thực",
"Citizenship":"Quyền công dân",
"Profile":"Hồ sơ",
"withdrawal_heading":"Rút tiền",
"register":"Đăng ký ngay",
"Bankwire_Deposit_Success":"Nạp tiền thành công",
"promoCodePlaceholder":"Mã khuyến mại (không bắt buộc)",
"get_email_otp":"Nhận email OTP",
"check your email":"Kiểm tra email của bạn",
"tosAgreeLabel":"Tôi đã đọc, hiểu và chấp nhận",
"termsOfServices":"Điều khoản dịch vụ",
"email_otp_sent":"Email OTP đã gửi",
"countryPlaceholder":" Country",
"phoneCodePlaceholder":"Mã điện thoại",
"phonePlaceholder":"Số điện thoại",
"getEmailOtp":"Nhận email OTP",
"emailOTPSent":"Email OTP đã gửi",
"newRegisterCaptchaMsg":"Bạn đã cố gắng đăng nhập quá nhiều lần bằng ID email không chính xác. Vui lòng xác minh danh tính của bạn bằng cách nhập các ký tự bạn nhìn thấy trong hình bên dưới",
"newRegisterCaptchaMsg2":"Để được hỗ trợ thêm, xin vui lòng liên hệ",
"typeTheText":"Gõ văn bản",
"Please_Select_Country":"Hãy chọn quốc gia của bạn",
"Please_Enter_Phone":"Hãy nhập số điện thoại của bạn",
"Please_Enter_PhoneCode":"Hãy nhập đầu số điện thoại quốc gia của bạn",
"Form_incomplete":"hãy điền hết các mục",
"Incorrect_Password":"Mật khẩu không hợp lệ",
"trade_Deposit_funds":"Nạp tiền",
"deposit_funds_start_trading":"Tiền ký quỹ để bắt đầu giao dịch",
"deposit_fund_easy":"Nạp tiền rất dễ dàng, nhanh chóng và không phải trả thêm phí. Bắt đầu thấp đến 5 đô la.",
"deposit_funds_now":"Gửi tiền ngay",
"note_portal":"Ghi chú",
"otpExpired":"OTP hết hạn. Vui lòng yêu cầu OTP một lần nữa",
"emailValidationErrorMessage":"Vui lòng nhập một địa chỉ email hợp lệ",
"emailAlreadyExists":"Email đã tồn tại",
"invalidPhoneNumber":"Số điện thoại của bạn không hợp lệ.",
"wrongOTP":"Sai OTP",
"invalidCaptcha":"CAPTCHA không hợp lệ",
"otpSentOnYourEmail":"OTP được gửi trên email của bạn",
"alreadyExists":"Ghi lại đã tồn tại",
"registrationFailed":"Đăng ký thất bại. Vui lòng thử lại.",
"operationFailed":"Một số lỗi xảy ra. Vui lòng thử lại.",
"spreadRewards":"Truyền bá và kiếm phần thưởng",
"referralText":"Khi ai đó đăng ký với liên kết giới thiệu duy nhất của bạn, bạn sẽ kiếm được hoa hồng trên khối lượng giao dịch của họ.",
"shareLink":"Chia sẻ liên kết giới thiệu của bạn",
"copy":"Sao chép",
"scanRQCode":"Quét mã QR này cho liên kết giới thiệu của bạn",
"invalidPromoCode":"Không thể chứa bảng chữ cái hoặc ký tự đặc biệt",
"manage-account":"Quản lý tài khoản của bạn",
"referral":"Giới thiệu",
"time-frame":"Khung thời gian",
"percentage":"Tính theo phần trăm",
"predict":"Dự đoán",
"languageName":"Tiếng Anh",
"AZ":" A-Z",
"passwordLengthValidation":" 8-31 ký tự",
"az":" a-z",
"passwordNumberValidation":"Chữ số",
"noSpecialCharacterLabel":"Không ký tự đặc biệt",
"enter-otp":"Nhập email OTP",
"signIn":"Đăng nhập",
"home":"Trang Chủ",
"loginHeading":"Chào mừng trở lại! Đăng nhập để bắt đầu giao dịch",
"already_using_crypto_countdown":"Đã sử dụng Countdown?",
"getStarted":"Bắt đầu",
"bannerHeadTitle":"Dự đoán xu hướng giá và kiếm được lợi nhuận lên tới 80%",
"bannerContent":"Countdown là một nền tảng giao dịch web thưởng cho bạn về việc dự đoán hướng định giá của tiền điện tử một cách chính xác. Nó đơn giản như nhấp lên hoặc xuống.",
"// bannersubContent":"Nó đơn giản như nhấp lên hoặc xuống.",
"subscribeText":"Tạo một tài khoản. Chỉ mất 30 giây.",
"topValue":"$ 950000 trở lên",
"topTraderText":"Được thanh toán trong tháng trước. Bắt đầu giao dịch và mang về nhà lợi nhuận lớn",
"topTraderHead ":"Thương nhân hàng đầu",
"whaleAssuredTitle ":" <brand name> Đảm bảo",
"whaleRiskFree ":"Tiền gửi an toàn 100%, lợi nhuận theo thời gian thực và rút tiền miễn phí",
"convenientPayments ":"Nhiều phương thức thanh toán",
"professionalWorldClassHead":"Sàn giao dịch đẳng cấp thế giới giúp bạn chiến thắng",
"onBodingText ":"Countdown giúp bạn dễ dàng kiếm được lợi nhuận hấp dẫn từ các khoản đầu tư của mình. Nó rất đơn giản, chính xác và an toàn cao. Với rút tiền nhanh chóng và giao dịch bằng một cú nhấp chuột, đây là cách tốt nhất để bạn đạt được vàng.",
"tradeUtmostHead":"Giao dịch với sự tự tin tối đa",
"tradeFirstHead":"Được tốt nhất của cả hai thế giới",
"tradeFirstText":"<brand name>với kinh nghiệm sâu sắc về tài chính truyền thống và đổi mới sáng tạo trong môi trường fintech đương đại mang đến cho bạn những điều tốt nhất của cả hai thế giới",
"tradeFirstHead2":"Lặn sâu trong tinh túy trading",
"tradeFirstText2":"Nhận hướng dẫn giao dịch miễn phí khi bạn đăng ký để hiểu những điều cơ bản về đếm ngược tiền điện tử.",
"hello_there":"Hãy cho chúng tôi biết thêm một chút về bản thân bạn",
"account_details":"Chi tiết tài khoản",
"contact_details":"Chi tiết liên lạc",
"security_details":"Chi tiết bảo mật",
"new_to_crypto_countdown ":"Chưa biết về Countdown",
"jing-sheng-textimonial":"Một ứng dụng tuyệt vời để giao dịch. Tôi đã giao dịch trong một thời gian dài trên sàn giao dịch và sử dụng nhiều nguồn thông tin khác nhau. Trong ứng dụng, rất nhiều thông tin hữu ích có sẵn. Quan trọng nhất, bạn có thể theo dõi số liệu thống kê.",
"read-more-reviews":"Đọc thêm đánh giá",
"copyright-text-content":"Không có phần nào của trang web này có thể được sao chép mà không có sự cho phép rõ ràng.",
"copyright-text":"Bản quyền © 2019 <brand name>. Đã đăng ký Bản quyền.",
"copyright-text-2":"Không có phần nào của trang web này có thể được sao chép mà không có sự cho phép rõ ràng.",
"stay-assured":"Hãy yên tâm. Bạn sẽ ở trong một công ty tốt!",
"Create_Password":"Tạo mật khẩu",
"xuxin-textimonial":"Tôi không biết điều gì quan trọng với các nhà môi giới, nhưng đối với tôi, điều quan trọng nhất là sự tin tưởng và trung thực. Tôi đã làm việc với <brand name> từ tháng 12 năm 2016. Lúc đầu, chiến lược của tôi không thực sự hiệu quả, nhưng gần đây tôi đã có thể kiếm được những lợi nhuận đáng kể, nhất quán.",
"houan-textimonial":"Tôi bắt đầu với $ 256,49 vào ngày 11 tháng 1. Đã rút $ 823,96 lợi nhuận vào ngày 12 tháng 2. Tôi thực hiện giao dịch vào ban đêm - không bao giờ vào ban ngày. Và nó cũng không phải là mỗi đêm. Tôi thích cách thay đổi giá được tính đến 6 chữ số thập phân, cho phép tôi đưa ra các giao dịch nhiều hơn.",
"usp-heading":"Crypto Count Down có thể là con đường dễ dàng để bạn thành công",
"usp-1-title":"Rút tiền nhanh",
"usp-1-des":"Rút tiền nhanh chóng với một loạt các phương pháp. Không có phí ẩn.",
"usp-2-title":"Thời hạn sử dụng linh hoạt",
"usp-2-des":"Chọn từ các khoảng thời gian 7 lần bắt đầu từ 60 giây đến một khoảng thời gian kéo dài một giờ.",
"usp-3-title":"Giao dịch khi đang di chuyển",
"usp-3-des":"Giao dịch mọi lúc, mọi nơi với ứng dụng của chúng tôi",
"usp-4-title":"Lợi nhuận cao",
"usp-4-des":"Với mức đầu tư tối thiểu thấp, kiếm được lợi nhuận lên tới 80%",
"usp-5-title":"Tailormade cho tiền mã hóa",
"usp-5-des":"Chỉ giao dịch đếm ngược dành riêng cho tiền điện tử",
"usp-6-title":"Giới thiệu và kiến tiền",
"usp-6-des":"Kế hoạch khen thưởng tốt nhất của ngành. Giới thiệu bạn bè của bạn và kiếm tiền hoa hồng ngay cả khi bạn không giao dịch",
"usp-7-title":"Thực hiện theo ví dụ",
"usp-7-des":"Thực hiện theo các nhà quản lý chiến lược hàng đầu. Chúng tôi làm cho con đường của bạn đến lợi nhuận đơn giản như đẩy một vài nút.",
"usp-8-title":"Lựa chọn rộng nhất của các cặp Countdown",
"usp-8-des":"Chọn đầu tư vào nhiều loại tiền điện tử khác nhau chỉ bằng vài cú nhấp chuột",
"support-heading":"Đặt cược tốt nhất của bạn để kiếm được lợi nhuận lớn thực sự dễ dàng.",
"support-1-title":"Chia sẻ lợi nhuận hấp dẫn",
"support-1-des":"Hãy là một phần của ngành công nghiệp chỉ trao đổi chia sẻ lợi nhuận giao dịch thông qua một hệ thống mã thông báo duy nhất",
"support-2-title":"Hỗ trợ LiveChat",
"support-2-des":"Bị mắc kẹt trong một giao dịch? Nhận hỗ trợ ngay lập tức với LiveChat",
"support-3-title":"Hướng dẫn giao dịch miễn phí",
"support-3-des":"Chúng tôi có thể hướng dẫn bạn. Hướng dẫn giao dịch miễn phí tất cả cho bạn khi bạn đăng ký",
"talking-about":"Ai khác đang nói về chúng tôi?",
"disclaimer":"Tuyên bố miễn trừ trách nhiệm",
"disclaimer-des":"Các hoạt động được cung cấp bởi trang web này có thể mang đến mức độ rủi ro cao và việc thực hiện chúng diễn ra trong một thị trường rất biến động. Trong trường hợp mua các công cụ tài chính do Trang web và Dịch vụ cung cấp, bạn có thể phải chịu tổn thất đáng kể về đầu tư hoặc thậm chí mất tất cả tiền trong Tài khoản của mình. Vui lòng thực hiện thận trọng và sử dụng sự phân biệt thận trọng của bạn trước khi quyết định đầu tư tiền vào thị trường.",
"shanghai":"Thượng hải",
"money-fair":"Hội chợ tiền",
"awards":"Giải thưởng",
"trader":"Thương nhân",
"choice":"Lựa chọn",
"demoAccountCannotProceed":"Chuyển sang tài khoản thật để tiếp tục",
"traningAccount":"Tài khoản demo",
"traningAccountContent":"Tài khoản đào tạo cho phép bạn giao dịch bằng tiền ảo. Nó mang số dư 100.000 USD. Bạn có thể rút tiền từ tài khoản đào tạo của bạn.",
"realAccount":"Tài khoản  của bạn",
"addMoney":"Thêm tiền",
"tryNow":"Thử ngay bây giờ",
"selectText":"Lựa chọn",
"selectedText":"Đã chọn",
"in-usd":" IN USD",
"brand-name":"Cá voi của tôi",
"fullName":"Họ và tên",
"Please_Enter_Name":"Vui lòng nhập tên đầy đủ",
"nameValidationErrorMessage":"Vui lòng nhập tên đầy đủ hợp lệ. Nó không thể chứa số hoặc ký tự đặc biệt",
'coachMarkStep1':'Chào mừng bạn đến với tài khoản demo của bạn. Khám phá cách giao dịch countdown tiền điện tử thực sự xảy ra mà không cần gửi bất kỳ khoản tiền thật nào.',
'coachMarkStep2':'Chọn một cặp tiền bạn muốn thử giao dịch',
'coachMarkStep3':'Đây là thời gian giao dịch của bạn sẽ diễn ra trong bao lâu và phần lợi nhuận bạn có thể kiếm được từ nó.',
'coachMarkStep4':'Chọn một số tiền bạn muốn đầu tư vào giao dịch này',
'coachMarkStep5':'Lợi nhuận hiển thị ở đây là tiền thắng tiềm năng của bạn cho giao dịch này',
'coachMarkStep6':'Dự đoán cặp tiền tệ đã chọn của bạn sẽ hoạt động như thế nào trong suốt thời gian giao dịch. Nó sẽ tăng lên hoặc nó sẽ trượt xuống? Nó đơn giản như vậy.',
'coachMarkStep7':'Khi sẵn sàng, bạn có thể chuyển sang tài khoản trực tiếp, ngay tại đây.',
'next':'Kế tiếp',
  'prev':'Trước',
  'done':'Done',
  'skip':'Skip',
  "releaseVersion": "Phát hành phiên bản",
  "orderId": "Số đơn hàng",
  "marketWatch": "Thời gian cập nhật mới nhất",
  "invalidPromoCodeValue": "Mã khuyến mại không được lớn hơn 2,147,483,647"
};
