// lang-en.ts

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'Crm_Login_Header': 'Login',//We are using 'Login' instead of 'Member Login'
  'Email-id': 'Email',//Email
  'Crm_Password': 'Password',
  'Crm_Validation_WrongEmailPwd': 'Invalid email or password',//Instead of Wrong Email-id / Password.
  'I_have_read_and_agree_to_the': 'I have read and agree to the',
  'Login_Please_Enter_Email_and_Password': 'Please enter email and password',
  'By_Logging_in_you_agree_to_our': 'By Logging in you agree to our ',
  'Privacy_Policy': 'privacy policy',
  'Crm_MT4_Submit': 'Submit',
  'Forgot_Password': 'Forgot password',
  'Verification_Link_Sent': 'Verification Link Sent',
  'Enter_valid_email': 'Enter valid email address',
  'Crm_Footer_Message': 'The timing and pricing displayed on these interfaces are largely dependent on the strength and stability of your internet connectivity.',
  'Please_Enter_Email': 'Please enter email',
  'Enter_Email': 'Enter email',
  'Please_Enter_Password': 'Please enter password',
  'Please_Accept_Privacy_Policy': 'Accept terms and conditions',//Instead of Please Accept Privacy Policy
  'Please_enter_your_registered_email': 'Please enter your registered email',//Instead of This Email Is Not Registered !
  'Getting_started_with': 'Getting started with',
  'web_tarder_carousel': 'Web Trader',
  'Light_up_your_phone_Trade': 'Light up your phone Trade...',
  'Anytime_Anywhere_carousel': 'Anytime. Anywhere',
  'The_Worlds_Most_Advanced': 'The World’s Most Advanced',
  'MT4_FX_Derivatives': 'MT4 FX Derivatives',
  'Binding_MT4_Account': 'MT4 Login',
  'MT4_Password': 'Password',
  'MT4_Remember_Me': 'Remember me',
  'Powered_by': 'Powered by ',
  'Back_to': 'Back to ',
  'Back_to_Login': 'Back to Login',
  'MT4_Submit': 'Submit',
  'Trade_Loading': 'Loading',
  'Trade_Profile': 'Profile',
  'Trade_Trading_History': 'TRADING HISTORY',
  'Trade_Deposit': 'Deposit',
  'Trade_Withdrawal': 'Withdrawal',
  'Trade_Settings': 'Settings',
  'Trade_Feedback': 'Feedback',
  'Trade_About_us': 'About us',
  'Trade_Logout': 'Logout',
  'Trade_Search': 'Search',
  'Trade_Favorites': 'Favorites',
  'Trade_No_Favorites': 'No favorites found',
  'Trade_Balance': 'Balance',
  'Trade_Open_Trades': 'OPEN TRADES',
  'Trade_History': 'HISTORY',
  'Trade_Amount': 'Amount',
  'Trade_Profit': 'Profit',
  'Trade_OK': 'OK',
  'Trade_UP': 'UP',
  'Trade_DOWN': 'DOWN',
  'Trade_Total_Exosure': 'Total Exposure',
  'Trade_One_Click_Trading': 'One click trading',
  'Trade_Sounds': 'Sounds',
  'Trade_Language': 'Language',
  'Trade_Chinese': 'Chinese',
  'Trade_Confirm_Trade': 'Confirm Trade',
  'Trade_Submit': 'Submit',
  'Trade_Close': 'Close',
  'Hist_Full_Trade_History': 'Full Trade History',
  'Hist_Showing': 'Showing',
  'Page_number' : '',
  'Hist_of': 'of',
  'Hist_Date': 'Date',
  'Hist_Symbol': 'Symbol',
  'Hist_Action': 'Action',
  'Hist_Open': 'Open',
  'Hist_Close': 'Close',
  'Hist_Amount': 'Amount',
  'Hist_Profit': 'Profit',
  'Hist_Interval': 'High Interval',
  'Hist_Result': 'Result',
  'Hist_No_History': 'No trade history found',
  'Hist_Loading': 'Loading',
  'Ind_BB': 'Bollinger Bands',
  'Ind_MACD': 'MACD',
  'Ind_Stochastic': 'Stochastic',
  'Ind_SMA': 'SMA',
  'Ind_RSI': 'RSI',
  'Ind_EMA': 'EMA',
  'Ind_SETTINGS': 'SETTINGS',
  'Ind_OK': 'OK',
  'Ind_Close': 'Close',
  'Open_Open_Positions': 'Open Positions',
  'Open_NO_Trade': 'There are no open trades',
  'Open_Open': 'Open',
  'Open_Close': 'Close',
  'Open_Amount': 'Amount',
  'Open_Profit': 'Profit',
  'Win': 'Win',
  'Loss': 'Loss',
  'Draw': 'Draw',
  'BB': 'BOLLINGER BANDS',
  'MACD': 'MACD',
  'STOCHASTIC': 'STOCHASTIC',
  'SMA': 'SMA',
  'RSI': 'RSI',
  'EMA': 'EMA',
  'OVERSOLD': 'OVERSOLD',
  'OVERBOUGHT': 'OVERBOUGHT',
  'Period': 'PERIOD',
  'UNDEFINED': 'UNDEFINED',
  'SIGNAL PERIOD': 'SIGNAL PERIOD',
  'FAST PERIOD': 'FAST PERIOD',
  'SLOW PERIOD': 'SLOW PERIOD',
  'PERIOD': 'PERIOD',
  'STANDARD DEVIATION': 'STANDARD DEVIATION',
  'K PERIOD': 'K PERIOD',
  'D PERIOD': 'D PERIOD',
  'Trade_Double_Up': 'Double Up',
  'Trade_Min_Amount': 'Min Amount',
  'Trade_Max_Amount': 'Max Amount',
  'Trade_Insufficient_Account_Balance': 'Insufficient account balance',
  'Trade_Amount_Range_1': 'The amount must be within the range of ',
  'Trade_Amount_Range_2': ' to ',
  'Trade_Amount_Range_3': ' ',
  'Trade_Amount_Multiples_Of': 'Amount must be multiple of ',
  'Trade_Amount_Multiples_Of_After': ' ',
  'Trade_Too_many_orders': 'Too many orders',
  'Trade_Market_is_closed': 'Market is closed',
  'Trade_Invalid_parameters': 'Invalid parameters',
  'Trade_Submit_order_failure': 'Order can not be placed currently',
  'Trade_Invalid_Amount': 'Invalid amount',
  'Trade_Account_Inactive': 'Your MT4 status is inactive, please contact customer service',
  'Internet_connection_is_slow': 'Slow Internet connection',
  'Internet_connection_is_lost_Reconnecting': 'Internet connection is lost. Reconnecting....',
  'Connecting': 'Connecting....',
  'Your_session_will_expire_in_next': 'Your session will expire in next',
  'Trade_seconds': 'seconds',
  'Trade_Not_enough_money': 'Insufficient balance',
  'Trade_Reached_Max_Chart_Tabs': 'Reached max chart tabs',
  'Trade_Order_placed_successfully': 'Order placed successfully',
  'The_Reset_Password_Link_has_been_sent_to_your_email': 'The reset password link has been sent to your email',
  'Please_Enter_email_address:': 'Please enter email address',
  'Trade_deposit_rediret': 'You will be redirected to CRM for Deposit.',
  'Trade_withdrawal_redirect': 'You will be redirected to CRM for Withdrawal.',
  'Trade_Sure': 'Sure',
  'Trade_not_now': 'Not now',
  'Trade_No_Symbols_Found': 'No symbols found',
  'Log_Out_Mssg': 'You will be logged out, do you want to continue ?',
  'MT4_Password_Incorrect': 'Incorrect password',
  'Max_Indicators': 'Maximum 3 indicators at a time are allowed',
  'Bookmark_Chart': 'Bookmark your favorite charts here',
  'Trade_Chart_Bookmarked': 'Chart is already bookmarked',
  'MACD_Fast_Period_Greater_Than_Slow_Period': 'Fast period should be lesser than slow period',
  'Bookmark_Added': 'Bookmark added',
  'Orientation_wait': 'Wait a moment...',
  'Orientation_rotate_landscape': 'Rotate the screen to landscape mode for better user experience.',
  'Orientation_note': 'NOTE: Please enable Auto-rotation of your device, if it is disabled.',
  'mobiledevice_line1': 'One stop Trading platform',
  'mobiledevice_line2': ' also available as Android app.',
  'mobiledevice_download_app': 'Download Now',
  'Verified': 'Verified',
  'Not_Verified': 'Not verified',
  'Citizenship': 'Citizenship',
  'Profile': 'Profile',
  'withdrawal_heading': 'Withdrawal',
  'register': 'Register Now',
  'Bankwire_Deposit_Success': 'Deposit has been submitted successfully!!',
  'promoCodePlaceholder': 'Promo Code (Optional)',
  'get_email_otp': 'Get Email OTP',
  'check your email': 'Check Your Email',
  'tosAgreeLabel': 'I have read, understood and accept the ',
  'termsOfServices': 'Terms Of Services',
  'email_otp_sent': 'Email OTP Sent',
  'countryPlaceholder': 'Country',
  'phoneCodePlaceholder': 'Phone Code',
  'phonePlaceholder': 'Phone Number',
  'getEmailOtp': 'Get Email OTP',
  'emailOTPSent': 'Email OTP Sent',
  'newRegisterCaptchaMsg': 'You have tried to log in too many times using an incorrect email ID. Please verify your identity by entering the characters you see in the picture below',
  'newRegisterCaptchaMsg2': 'For further assistance, please contact',
  'typeTheText': 'Type the text',
  'Please_Select_Country': 'Please select your country',
  'Please_Enter_Phone': 'Please enter phone number',
  'Please_Enter_PhoneCode': 'Please enter your country phone code',
  'Form_incomplete': 'Please fill all the fields',
  'Incorrect_Password': 'Invalid password',
  'trade_Deposit_funds': 'Make Deposit',
  'deposit_funds_start_trading': 'Deposit Funds to Start Trading',
  'deposit_fund_easy': ' Depositing funds is easy, fast, and it comes with no extra charges. Start as low as $5.',
  'deposit_funds_now': 'Deposit Funds Now',
  'note_portal': 'Note: You’ll be redirected to',
  'otpExpired': 'OTP expired. Please request an OTP again',
  'emailValidationErrorMessage': 'Please enter a valid email address',
  'emailAlreadyExists': 'Email Already Exists',
  'invalidPhoneNumber': 'Your mobile number is invalid.',
  'wrongOTP': 'Wrong OTP',
  'invalidCaptcha': 'Invalid CAPTCHA',
  'otpSentOnYourEmail': 'OTP sent on your email',
  'alreadyExists': 'Record Already Exists',
  'registrationFailed': 'Registration failed. Please try again.',
  'operationFailed': 'Some error occurred. Please try again.',
  'spreadRewards':'Spread the word and earn rewards',
  'referralText':'When someone signs up with your unique referral link, you stand to earn commission on their trading volume.',
  'shareLink':'Share your referral link',
  'copy':'Copy',
  'scanRQCode':'Scan this QR code for your referral link',
  'invalidPromoCode': 'Cannot contain alphabets or special character',
  'manage-account': 'Manage your account',
  'referral': 'Referral',
  'time-frame': 'Time Frame',
  'percentage': 'In percentage',
  'predict':'Predict',
  'languageName': 'English',
  "AZ": "A-Z",
  "passwordLengthValidation": "8-31 Characters",
  "az": "a-z",
  "passwordNumberValidation": "Numbers",
  'noSpecialCharacterLabel': "No Special Characters",
  'enter-otp': 'Enter Email OTP',
  'signIn': 'Sign In',
  'home': 'Home',
  'loginHeading':'Welcome back! Log in to start trading',
  'already_using_crypto_countdown': 'Already using Countdown?',
  'getStarted': 'Get Started',
  'bannerHeadTitle': 'Predict price trends and earn up to 80% returns',
  'bannerContent': 'Countdown is a web trading platform that rewards you on predicting the pricing direction of crypto currency correctly. It\'s as simple as clicking up or down.',
  // 'bannersubContent': 'It\'s as simple as clicking up or down.',
  'subscribeText': 'Create an account. It takes just 30 seconds.',
  'topValue': '$ 950000+',
  'topTraderText': 'Paid out in the last month. Start trading and take-home big returns',
  'topTraderHead' : ' Top Traders',
  'whaleAssuredTitle' : 'Whale Assured',
  'whaleRiskFree' : '100% safe deposits, Real-time profits and Hassle-free withdrawals',
  'convenientPayments' : 'Multiple payment methods',
  'professionalWorldClassHead': 'World class trading platform that makes you win',
  'onBodingText' : 'Countdown makes it easy for you to earn attractive returns on your investments. It’s simple, precise, and highly secure. With quick withdrawals and one-click trading, this is your best bet to strike gold.',
  'tradeUtmostHead': 'Trade with utmost confidence',
  'tradeFirstHead':'Get the best of both worlds',
  'tradeFirstText':'Whale’s deep-rooted experience in traditional finance and trailblazing innovation in the contemporary fintech environment gives you the best of both the worlds',
  'tradeFirstHead2':'Deep dive in trading essentials',
  'tradeFirstText2':'Get a free trading guide when you sign up to understand the basics of Countdown.',
  'hello_there': 'Hey there! Tell us a bit more about yourself',
  'account_details': 'Accout Details',
  'contact_details': 'Contact Details',
  'security_details': 'Security Details',
  'new_to_crypto_countdown' : 'New to Countdown',
  'jing-sheng': 'Jing Sheng',
  'jing-sheng-textimonial': 'An excellent application for trading. I have been trading for a long time on the exchange and use various sources of information. In the application, a lot of useful information is available. Most importantly, you can track statistics.',
  'read-more-reviews': 'Read more reviews',
  'copyright-text-content': 'No portion of this website may be reproduced without expressed permission.',
  'copyright-text': ' Copyright © 2019 Whale Inc. All rights reserved.',
  'copyright-text-2': 'No portion of this website may be reproduced without expressed permission.',
  'stay-assured': 'Stay assured. You‘ll be in good company!',
  'Create_Password': 'Create Password',
  'xuxin': 'Xu Xin',
  'xuxin-textimonial': 'I don\'t know what\'s important to brokers, but for me the most important things are trust and honesty. I have worked with Whale-inc.com since December 2016. At the start, my strategy was not really working, but recently I was able to make consistent, substantial gains.',
  'houan': 'Hou An',
  'houan-textimonial': 'I started with $257.49 on January 11th. Withdrew $823.96 of profit on February 12th. I make trades at night - never during the day. And it is not every night either. I like how price changes are calculated to 6 decimal places, letting me come out ahead on more deals.',
  'usp-heading': 'Crypto Count Down can be your easy route to success',
  'usp-1-title': 'Quick Withdrawals',
  'usp-1-des': 'Withdraw funds quickly with a range of methods. No hidden fee.',
  'usp-2-title': 'Flexible Expiry Times',
  'usp-2-des': 'Choose from 7-time intervals that start from a mere 60 seconds to an extended period of an hour.',
  'usp-3-title': 'Trade on the go',
  'usp-3-des': 'Trade anytime, anywhere with our app',
  'usp-4-title': 'High Returns',
  'usp-4-des': 'With low minimum investment, earn returns of up to 80%',
  'usp-5-title': 'Tailormade for Crypto',
  'usp-5-des': 'Only countdown trader dedicated to cryptocurrency',
  'usp-6-title': 'Refer and Earn',
  'usp-6-des': 'Industry\'s best referral reward plan. Refer your friends and earn commissions even when you’re not trading',
  'usp-7-title': 'Follow with Example',
  'usp-7-des': 'Follow leading strategy managers. We make your path to profits as simple as pushing a few buttons.',
  'usp-8-title': 'Widest Choice of Countdown Pairs',
  'usp-8-des': 'Choose to invest in a variety of crypto currencies in just a few clicks',
  'support-heading': 'Your best bet to earn great returns really easily.',
  'support-1-title': 'Attractive Profit Sharing',
  'support-1-des': 'Be a part of industry’s only exchange that shares trading profits through a unique token system',
  'support-2-title': 'LiveChat Support',
  'support-2-des': 'Stuck during a trade? Get instant support with LiveChat',
  'support-3-title': 'Free Trading Guide',
  'support-3-des': 'We’re there to guide you. Free know-it-all trading guide for you as you sign up',
  'talking-about': 'Who else is talking about us?',
  'disclaimer': 'Disclaimer',
  'disclaimer-des': 'The operations provided by this site may carry high level of risks, and their execution takes place in a highly volatile market. In case of purchase of financial instruments offered by the Website and the Services, you may incur significant losses of investment or even lose all funds on your Account. Please execute due caution and employ your judicious discernment before deciding to invest funds in the market.',
   'shanghai': 'Shanghai',
   'money-fair': 'Money Fair',
   'awards': 'Awards',
   'trader': 'Trader',
   'choice': 'Choice',
  'demoAccountCannotProceed':'Switch to real account to proceed',
   'traningAccount':'Training Account',
   'traningAccountContent':'A training account allows you to trade using virtual money. It carries a balance of 10000(USD). You can’t withdraw funds from your training account.',
   'realAccount':'Your accounts',
   'addMoney': 'Add Money',
   'tryNow': 'Try Now',
   'selectText': 'Select',
   'selectedText': 'Selected',
   'in-usd': 'IN USD',
   'brand-name': 'myWhale',
   'fullName': 'Full Name',
   'Please_Enter_Name': 'Please enter Full Name',
   'nameValidationErrorMessage': 'Please enter a valid Full Name. It cannot contain numbers or special characters',
   'country': 'Country',
   'coachMarkStep1':'Welcome to your demo account. Explore how real countdown trades happen without depositing any real money.',
   'coachMarkStep2':'Choose a currency pair you want to try trading on.',
   'coachMarkStep3':'This is how long your trade will go on for, and the profit % you stand to earn from it.',
   'coachMarkStep4':'Choose an amount you would like to invest in this trade.',
   'coachMarkStep5':'The profit shown here are your potential winnings for this trade',
   'coachMarkStep6':'Predict how your chosen symbol will behave during the duration of the trade. Is it going to rise up or will it slide down? It is as simple as that.',
   'coachMarkStep7':'When ready, you can switch to a live account, right here.',
   'next':'Next',
   'prev':'Prev',
   'done':'Done',
   'skip':'Skip',
   "releaseVersion": "Release Version",
   "orderId": "Order ID",
   "marketWatch": "Market Watch",
   "invalidPromoCodeValue": "Promocode should not be greater than 2,147,483,647"
};
