export const LANG_KO_NAME = 'ko';

export const LANG_KO_TRANS = {

'Crm_Login_Header':'로그인',
'Email-id':'이메일',
'Crm_Password':'비밀번호',
'Crm_Validation_WrongEmailPwd':'존재하지 않는 이메일주소 및 비밀번호입니다',
'I_have_read_and_agree_to_the':'다음의 사항을 모두 확인했으며 이에 동의합니다',
'Login_Please_Enter_Email_and_Password':'이메일주소와 비밀번호를 입력해주세요',
'By_Logging_in_you_agree_to_our':'로그인시 저희의 정책에 동의하는 것으로 간주합니다',
'Privacy_Policy':'개인정보 보호정책',
'Crm_MT4_Submit':'로그인',
'Forgot_Password':'비밀번호 찾기',
'Verification_Link_Sent':'인증 링크가 발송되었습니다',
'Enter_valid_email':'정확한 이메일 주소를 입력해주세요',
'Crm_Footer_Message':'이 시스템 내에서 표시되는 가격 및 시간은 개인의 인터넷 연결강도 및 안정성의 환경에 따라 다르게 표시될 수 있습니다. ',
'Please_Enter_Email':'이메일 주소를 입력해 주세요',
'Enter_Email':'이메일주소 입력',
'Please_Enter_Password':'비밀번호를 입력해 주세요',
'Please_Accept_Privacy_Policy':'이용약관 동의 ',
'Please_enter_your_registered_email':'등록된 이메일 주소를 입력해주세요 ',
'Getting_started_with':'시작합니다 ',
'web_tarder_carousel':'웹 트레이더',
'Light_up_your_phone_Trade':'모바일 거래 시작',
'Anytime_Anywhere_carousel':'언제 어디서나',
'The_Worlds_Most_Advanced':'세계에서 가장 혁신적인',
'MT4_FX_Derivatives':'카운트다운 바이너리옵션',
'Binding_MT4_Account':'거래 계좌 로그인 ',
'MT4_Password':'비밀번호',
'MT4_Remember_Me':'로그인 정보 기억',
'Powered_by':'공급자',
'Back_to':'돌아가기',
'Back_to_Login':'로그인창으로 돌아가기',
'MT4_Submit':'제출',
'Trade_Loading':'로딩중',
'Trade_Profile':'프로필',
'Trade_Trading_History':'거래 내역',
'Trade_Deposit':'증거금',
'Trade_Withdrawal':'출금',
'Trade_Settings':'설정',
'Trade_Feedback':'피드백 ',
'Trade_About_us':'소개 ',
'Trade_Logout':'로그아웃',
'Trade_Search':'검색 ',
'Trade_Favorites':'즐겨찾기',
'Trade_No_Favorites':'즐겨찾기 내역이 없습니다 ',
'Trade_Balance':'잔액',
'Trade_Open_Trades':'거래현황',
'Trade_History':'과거 ',
'Trade_Amount':'금액',
'Trade_Profit':'이익 ',
'Trade_OK':'확인',
'Trade_UP':'매수',
'Trade_DOWN':'매도 ',
'Trade_Total_Exosure':'전체 보유 중 거래',
'Trade_One_Click_Trading':'원 클릭거래 ',
'Trade_Sounds':'소리 ',
'Trade_Language':'언어',
'Trade_Chinese':'중국어 한국어',
'Trade_Confirm_Trade':'거래 승인 ',
'Trade_Submit':'주문​',
'Trade_Close':'종료 ',
'Hist_Full_Trade_History':'전체 거래내역',
'Hist_Showing':'보여주기',
'Page_number ':'페이지 번호 ',
'Hist_of':'Hist(과거)~의',
'Hist_Date':'날짜 ',
'Hist_Symbol':'종목',
'Hist_Action':'활동',
'Hist_Open':'진입',
'Hist_Close':'종료 ',
'Hist_Amount':'금액',
'Hist_Profit':'수익 ',
'Hist_Interval':'거래단위​',
'Hist_Result':'결과 ',
'Hist_No_History':'거래 내역을 찾을 수 없습니다 ',
'Hist_Loading':'로딩중',
'Ind_BB':'볼린저 밴드 ',
'Ind_MACD':'MACD',
'Ind_Stochastic':'스토캐스틱',
'Ind_SMA':'단순이동평균선',
'Ind_RSI':'RSI',
'Ind_EMA':'지수이동평균선',
'Ind_SETTINGS':'설정',
'Ind_OK':'확인 ',
'Ind_Close':'종료 ',
'Open_Open_Positions':'진입중 포지션',
'Open_NO_Trade':'진입중인 주문이 없습니다 ',
'Open_Open':'진입',
'Open_Close':'종료 ',
'Open_Amount':'금액',
'Open_Profit':'수익',
'Win':'수익',
'Loss':'손실',
'Draw':'동등',
'BB':'볼린저 밴드 ',
'MACD':'MACD',
'STOCHASTIC':'스토캐스틱',
'SMA':'단순이동평균선',
'RSI':'RSI',
'EMA':'지수이동평균선',
'OVERSOLD':'과매도',
'OVERBOUGHT':'과매수',
'Period':'기간 ',
'UNDEFINED':'찾을 수 없습니다',
'SIGNAL PERIOD':'',
'FAST PERIOD':'',
'SLOW PERIOD':'',
'PERIOD':'기간 ',
'STANDARD DEVIATION':'표준편차',
'K PERIOD':'',
'D PERIOD':'',
'Trade_Double_Up':'2배로 늘리기 ',
'Trade_Min_Amount':'최소금액',
'Trade_Max_Amount':'최대금액',
'Trade_Insufficient_Account_Balance':'계정 잔액부족',
'Trade_Amount_Range_1':'금액은 다음 범위 내에 있어야 합니다',
'Trade_Amount_Range_2':'까지',
'Trade_Amount_Range_3':' ',
'Trade_Amount_Multiples_Of':'금액은 다음의 몇 배가 필요합니다.',
'Trade_Amount_Multiples_Of_After':'',
'Trade_Too_many_orders':'주문초과',
'Trade_Market_is_closed':'장이 마감되었습니다 ',
'Trade_Invalid_parameters':'잘못된 한도',
'Trade_Submit_order_failure':'현재 주문할 수 없습니다',
'Trade_Invalid_Amount':'유효하지 않은 금액',
'Trade_Account_Inactive':'MT4 상태가 비활성입니다. 고객 서비스에 문의하십시오',
'Internet_connection_is_slow':'인터넷 연결 느림',
'Internet_connection_is_lost_Reconnecting':'인터넷 연결이 끊겼습니다. 재접속을 시도합니다… ',
'Connecting':'접속중…',
'Your_session_will_expire_in_next':'거래시간이 다음 시간 내에 만료됩니다.',
'Trade_seconds':'초',
'Trade_Not_enough_money':'잔액부족',
'Trade_Reached_Max_Chart_Tabs':'최대 차트 탭에 도달함',
'Trade_Order_placed_successfully':'주문이 정상적으로 체결되었습니다 ',
'The_Reset_Password_Link_has_been_sent_to_your_email':'비밀번호 재설정 링크가 이메일로 발송되었습니다 ',
'Please_Enter_email_address':'이메일 주소를 입력해주세요',
'Trade_deposit_rediret':'입금을 위해 고객페이지로 연결됩니다 ',
'Trade_withdrawal_redirect':'출금을 위해 고객페이지로 연결됩니다 ',
'Trade_Sure':'확인',
'Trade_not_now':'다음에',
'Trade_No_Symbols_Found':'종목을 찾을 수 없습니다 ',
'Log_Out_Mssg':'로그아웃 예정입니다. 계속할까요? ',
'MT4_Password_Incorrect':'잘못된 비밀번호',
'Max_Indicators':'한 번에 최대 3개의 보조지표 허용',
'Bookmark_Chart':'차트 즐겨찾기 추가',
'Trade_Chart_Bookmarked':'차트 즐겨찾기 추가 이미 완료',
'MACD_Fast_Period_Greater_Than_Slow_Period':'빠른 기간은 느린 기간보다 짧아야합니다',
'Bookmark_Added':'즐겨찾기가 추가되었습니다 ',
'Orientation_wait':'잠시만 기다려주세요',
'Orientation_rotate_landscape':'더 나은 사용자 환경을 위해 화면을 가로 모드로 돌리십시오',
'Orientation_note':'참고',
'mobiledevice_line1':'원스탑 트레이딩 플랫폼',
'mobiledevice_line2':'안드로이드 앱으로도 이용가능합니다',
'mobiledevice_download_app':'지금 다운로드 ',
'Verified':'검증 완료 ',
'Not_Verified':'검증되지 않음 ',
'Citizenship':'시민권',
'Profile':'프로픨',
'withdrawal_heading':'출금',
'register':'회원가입',
'Bankwire_Deposit_Success':'입금이 성공적으로 완료되었습니다 ',
'promoCodePlaceholder':'프로모션 코드',
'get_email_otp':'이메일로 OTP 받기 ',
'check your email':'이메일을 확인하세요',
'tosAgreeLabel':'나는 다음 내용을 읽고 이해 및 승인합니다',
'termsOfServices':'이용약관 ',
'email_otp_sent':'이메일로 OTP 전송함',
'countryPlaceholder':'국가 ',
'phoneCodePlaceholder':'국가번호 ',
'phonePlaceholder':'전화번호 ',
'getEmailOtp':'이메일로 OTP 받기 ',
'emailOTPSent':'이메일로 OTP 전송함',
'newRegisterCaptchaMsg':'잘못된 이메일 ID를 사용하여 너무 많이 로그인하려고 시도하셨습니다. 아래 그림에 표시된 문자를 입력하여 본인을 인증하십시오.',
'newRegisterCaptchaMsg2':'추가로 도움이 필요하실 경우 다음으로 연락하세요',
'typeTheText':'내용입력',
'Please_Select_Country':'국가를 선택해주세요 ',
'Please_Enter_Phone':'핸드폰 번호를 입력해주세요 ',
'Please_Enter_PhoneCode':'국가번호를 입력하세요',
'Form_incomplete':'모든 정보를 빠짐없이 입력해주세요 ',
'Incorrect_Password':'유효하지 않은 비밀번호',
'trade_Deposit_funds':'입금하기 ',
'deposit_funds_start_trading':'거래 시작를 위해 입금하세요',
'deposit_fund_easy':'자금 입금은 쉽고 빠르며 추가 비용이 들지 않습니다. 최저 $5 부터 시작하십시오.',
'deposit_funds_now':'지금 입금하기 ',
'note_portal':'고객서비스 페이지로 이동합니다',
'otpExpired':'OTP가 만료되었습니다. 다시 OTP를 요청하십시오',
'emailValidationErrorMessage':'정확한 이메일 주소를 입력해주세요 ',
'emailAlreadyExists':'이미 가입되어 있는 이메일 주소입니다 ',
'invalidPhoneNumber':'유효하지 않은 핸드폰 번호입니다 ',
'wrongOTP':'잘못된 OTP',
'invalidCaptcha':'유효하지 않은 보안문자  ',
'otpSentOnYourEmail':'이메일로 OTP가 발송되었습니다 ',
'alreadyExists':'이미 존재하는 기록입니다 ',
'registrationFailed':'등록 실패. 다시 시도해 주세요 ',
'operationFailed':'에러가 발생했습니다. 다시 시도해주세요 ',
'spreadRewards':'소개하고 보상받기',
'referralText':'누군가 귀하의 고유 추천 링크에 가입하면 거래량에 대한 수수료를 받게됩니다.',
'shareLink':'추천 링크 공유 ',
'copy':'복사 ',
'scanRQCode':'QR 코드를 스캔하여 추천 링크를 찾으십시오',
'invalidPromoCode':'알파벳이나 특수 문자를 포함 할 수 없습니다',
'manage-account':'계정 관리',
'referral':'추천',
'time-frame':'거래 만기 시간',
'percentage':'배당률',
'predict':'거래',
'languageName':'한국어',
'AZ':'A-Z',
'passwordLengthValidation': '8~31글자 사이',
'az':'a-z',
'passwordNumberValidation': '숫자',
'noSpecialCharacterLabel': '특수문자 사용이 불가능합니다',
'enter-otp': '이메일 OTP 입력',
'signIn':'로그인',
'home':'홈',
'loginHeading':'환영합니다! 거래 시작을 위해 로그인해주세요 ',
'already_using_crypto_countdown':'바이너리 옵션을 이미 사용하고 있습니까?',
'getStarted':'시작하기 ',
'bannerHeadTitle':'가격 추세를 예측하고 최대 80 %의 수익을 올리십시오',
'bannerContent':'바이너리 옵션은 사용 가능한 거래 쌍의 가격 방향을 예측하는 것에 대한 보상을 제공하는 웹 방식 거래 플랫폼입니다. 매수 또는 매도를 클릭하는 것만큼 간단합니다.',
'// bannersubContent':'매수 또는 매도를 클릭하는 것만 큼 간단합니다.',
'subscribeText':'계정을 생성하세요. 30초면 됩니다.',
'topValue':' $ 950000+',
'topTraderText':'지난 달에 지불했습니다. 거래를 시작하고 큰 수익을 내십시오',
'topTraderHead ':'탑 트레이더들',
'whaleAssuredTitle ':'확실한 <brand name>',
'whaleRiskFree ':'100 % 안전 입금, 실시간 수익 및 간단한 출금',
'convenientPayments ':'다양한 결제 방식 ',
'professionalWorldClassHead':'당신의 수익을 보장하는 세계적 수준의 거래 플랫폼',
'onBodingText ':'바이너리 옵션을 통해 투자에서 매력적인 수익을 쉽게 얻을 수 있습니다. 간단하고 정확하며 보안성이 매우 우수합니다. 빠른 인출과 원클릭 트레이딩으로, 수익을 얻는 가장 좋은 방법입니다.',
'tradeUtmostHead':'안심하고 거래하셔도 좋습니다 ',
'tradeFirstHead':'',
'tradeFirstText':'현대의 핀테크 환경에서 전통적 금융과 혁신적인 혁신에 대한 <Brand name>의 뿌리 깊은 경험은 당신에게 최고의 환경을 제공합니다',
'tradeFirstHead2':'거래 필수사항에 대해서 자세히 알아보기 ',
'tradeFirstText2':'회원가입시 가상화폐 바이너리옵션 시스템의 기본 기능을 이해하실 수 있도록 거래 안내문을 무료로 제공합니다',
'hello_there':'',
'account_details':'계좌 상세',
'contact_details':'고객센터 ',
'security_details':'보안 상세 ',
'new_to_crypto_countdown ':'바이너리 옵션이 처음입니다',
'jing-sheng-textimonial':'훌륭한 응용프로그램, 거래소에서 오랫동안 거래하며 다양한 정보의 소스를 이용하고 있다. 어플리케이션에서는, 많은 유용한 정보를 이용할 수 있으며, 가장 중요한 것은 통계를 추적할 수 있다는 것이다.',
'read-more-reviews':'더 많은 후기 읽기 ',
'copyright-text-content':'이 웹 사이트의 어떠한 부분도 명시적인 허가없이 복제 할 수 없습니다.',
'copyright-text':'  Copyright © 2020 <brand name>. All rights reserved.',
'copyright-text-2':'이 웹 사이트의 어떠한 부분도 명시적인 허가없이 복제 할 수 없습니다.',
'stay-assured':'',
'Create_Password':'비밀번호 생성 ',
'xuxin-textimonial':'',
'houan-textimonial':'',
'usp-heading':'',
'usp-1-title':'빠른 출금 ',
'usp-1-des':'다양한 방법으로 자금을 신속하게 인출 할 수 있습니다. 숨겨진 수수료가 없습니다.',
'usp-2-title':'유연한 만료 시간',
'usp-2-des':'60초에서 1시간까지 7개 만료일 중에서 선택하십시오.',
'usp-3-title':'거래 시작하기',
'usp-3-des':'언제 어디서나 앱을 통해 거래하세요',
'usp-4-title':'높은 수익률',
'usp-4-des':'낮은 증거금 투자로 최대 80%까지 수익실현이 가능합니다',
'usp-5-title':'Crypto에 최적화',
'usp-5-des':'',
'usp-6-title':'추천 그리고 수익',
'usp-6-des':'업계 최고의 추천 보상 계획. 거래하지 않을 때도 친구를 추천하고 수수료를받습니다',
'usp-7-title':'다음 예를 따르십시오',
'usp-7-des':'당신의 전략 매니저를 믿고 따르세요! 가장 쉽고 빠른 수익 실현 방법을 안내해드립니다',
'usp-8-title':'다양한 바이너리옵션 종목 선택',
'usp-8-des':'몇 번의 클릭만으로 다양한 가상화폐 및 환율 중 선택, 투자하세요',
'support-heading':'큰 수익을 얻을 수 있는 가장 멋진 방법',
'support-1-title':'매력적인 수익 창출',
'support-1-des':'업계 최고의 추천 보상 계획. 거래하지 않을 때에도 친구에게 추천하고 수수료를 받으세요.',
'support-2-title':'실시간 채팅 지원',
'support-2-des':'거래 중 문제가 발생하셨다면 실시간 채팅을 통해 도움을 받아보세요',
'support-3-title':'무료 거래 안내',
'support-3-des':'회원가입시 매니저를 통해 무료로 전문적인 상담 및 안내를 받으실 수 있습니다',
'talking-about':'',
'disclaimer':'권리 포기 각서',
'disclaimer-des':'이 사이트에서 제공되는 거래는 매우 변동성이 높은 시장에서 이뤄지기 때문에 높은 위험성을 수반할 수 있습니다. 웹 사이트 내에서 제공되는 서비스 및 금융 거래를 통해 예탁한 증거금의 대부분 또는 전액을 손실로 상실할 수 있습니다. 거래를 시작하시기 전에 본인의 재산상황 등을 충분히 감안하여 거래 여부를 신중히 결정하시기 바랍니다. ',
'shanghai':'',
'money-fair':'',
'awards':'보상',
'trader':'트레이더',
'choice':'선택 ',
'demoAccountCannotProceed':'계속하려면 실제 계정으로 전환',
'traningAccount':'교육 계정',
'traningAccountContent':'모의 투자 계좌는 가상 통화를 통해  매매를 체험하실 수 있습니다. 10000(USD)가 기본으로 세팅되어 있으며 모의계좌에서는 출금이 불가능합니다 ',
'realAccount':'실투자 계좌',
'addMoney':'돈을 추가',
'tryNow':'바로 실행 ',
'selectText':'선택 ',
'selectedText':'선택완료',
'in-usd':'달러통화',
'brand-name':'보맥스',
'fullName':'이름',
'Please_Enter_Name':'성함을 입력해주세요',
'nameValidationErrorMessage':'올바른 이름을 입력해주세요. 특수문자나 숫자는 입력하실 수 없습니다',
'country' : '국가',
'coachMarkStep1':'데모 계정에 오신 것을 환영합니다. 실제 돈을 입금하지 않고 실제 바이너리 옵션 거래가 어떻게 진행되는지 살펴보십시오.',
'coachMarkStep2':'거래하기를 원하는 종목을 선택해주세요',
'coachMarkStep3':'여기서 남거래 만기시간 및 배당률을 확인 가능합니다',
'coachMarkStep4':'거래를 원하는 금액을 선택해주세요',
'coachMarkStep5':'여기에서 나오는 이익은, 이 거래를 통한 거래 수익 배당금이다.',
'coachMarkStep6':'남은 계약 시간동안 당신이 선택한 통화쌍의 움직임을 예측해보세요. 상승할까요? 하락할까요? 이렇게 간단합니다.',
'coachMarkStep7':'준비되면 바로 여기에서 실 계정으로 전환할 수 있습니다.',
'next':'다음',
  'prev':'이전',
  'done':'Done',
  'skip':'Skip',
  "releaseVersion": "버젼 풀기",
  "orderId": "주문 아이디",
  "marketWatch": "시장 감시",
  "invalidPromoCodeValue": "프로모션 코드는 2,147,483,647보다 클 수 없습니다."
};
